# Generated by Django 2.2 on 2022-01-03 06:11

from django.db import migrations, models
import youtubeApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('channel_name', models.CharField(max_length=30)),
                ('profile', models.FileField(null=True, upload_to=youtubeApp.models.get_profile_path)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
