# Generated by Django 2.2 on 2022-01-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(null=True, upload_to='images/profiles/'),
        ),
    ]
