# Generated by Django 2.2 on 2022-01-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0002_auto_20220103_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(default='something', upload_to='images/profiles/'),
            preserve_default=False,
        ),
    ]
