# Generated by Django 2.2 on 2022-01-03 07:31

from django.db import migrations, models
import youtubeApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0003_auto_20220103_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(null=True, upload_to=youtubeApp.models.get_profile_path),
        ),
    ]
