# Generated by Django 2.2 on 2022-01-04 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0007_auto_20220104_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(default='something', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='youtubeApp.User'),
            preserve_default=False,
        ),
    ]
