# Generated by Django 2.2 on 2022-01-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0009_auto_20220104_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_whom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liked_videos', to='youtubeApp.User')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='youtubeApp.Video')),
            ],
        ),
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_whom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disliked_videos', to='youtubeApp.User')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='youtubeApp.Video')),
            ],
        ),
    ]
