# Generated by Django 2.2 on 2022-01-06 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0012_auto_20220106_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='video_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
